package org.hussain.workspace.builders.facebook.enums;

public enum TrackingSpec {
	CANVAS_APP_ENGAGEMENT("CANVAS_APP_ENGAGEMENT"), CANVAS_APP_INSTALLS(
			"CANVAS_APP_INSTALLS"), EVENT_RESPONSES("EVENT_RESPONSES"), MOBILE_APP_ENGAGEMENT(
			"MOBILE_APP_ENGAGEMENT"), MOBILE_APP_INSTALLS("MOBILE_APP_INSTALLS"), OFFER_CLAIMS_BIDDING(
			"OFFER_CLAIMS_BIDDING"), OFFER_CLAIMS_NONBIDDING(
			"OFFER_CLAIMS_NONBIDDING"), PAGE_LIKES_BIDDING("PAGE_LIKES_BIDDING"), PAGE_LIKES_NONBIDDING(
			"PAGE_LIKES_NONBIDDING"), POST_ENGAGEMENT("POST_ENGAGEMENT"), WEBSITE_CLICKS_BIDDING(
			"WEBSITE_CLICKS_BIDDING"), WEBSITE_CLICKS_NONBIDDING(
			"WEBSITE_CLICKS_NONBIDDING"), WEBSITE_CLICKS_DOMAINAD_BIDDING(
			"WEBSITE_CLICKS_DOMAINAD_BIDDING"), WEBSITE_CLICKS_DOMAINAD_NONBIDDING(
			"WEBSITE_CLICKS_DOMAINAD_NONBIDDING"), WEBSITE_CONVERSIONS_BIDDING(
			"WEBSITE_CONVERSIONS_BIDDING"), WEBSITE_CONVERSIONS_NONBIDDING(
			"WEBSITE_CONVERSIONS_NONBIDDING"), WEBSITE_CONVERSIONS_DOMAINAD_BIDDING(
			"WEBSITE_CONVERSIONS_DOMAINAD_BIDDING"), WEBSITE_CONVERSIONS_DOMAINAD_NONBIDDING(
			"WEBSITE_CONVERSIONS_DOMAINAD_NONBIDDING");

	private String trackingSpec;

	TrackingSpec(String trackingSpec) {
		this.trackingSpec = trackingSpec;
	}

	public String getTrackingSpec() {
		return trackingSpec;
	}
}
